// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxdHgHqoQwmUsxOyylUPFaiQCvxArsM5A',
    appId: '1:276763985365:web:3b31d0c5781c94cf0da95c',
    messagingSenderId: '276763985365',
    projectId: 'kongossa-d1442',
    authDomain: 'kongossa-d1442.firebaseapp.com',
    storageBucket: 'kongossa-d1442.firebasestorage.app',
    measurementId: 'G-6KVH0ZCKXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5XMDkrZErIy6LYJryAwGqfDecgyjZ4qw',
    appId: '1:276763985365:android:30f5a5562d88ad5f0da95c',
    messagingSenderId: '276763985365',
    projectId: 'kongossa-d1442',
    storageBucket: 'kongossa-d1442.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwKXnbvm3zvPutdXdb8ufa4KO9Mn4fyQ',
    appId: '1:276763985365:ios:08e7241fc1b93d060da95c',
    messagingSenderId: '276763985365',
    projectId: 'kongossa-d1442',
    storageBucket: 'kongossa-d1442.firebasestorage.app',
    iosBundleId: 'com.example.kongossaapp',
  );
}
